---
- name: Setting Up Server 2 
  hosts: server2
  strategy: free
  gather_facts: False
  ignore_errors: true
  tasks:
  - name: Setting Up Python
    file:
      src: /usr/bin/python3.6
      path: /usr/bin/python
      state: link
  - name: Setting Hostname
    hostname: name=server2.example.com
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.151/24 ipv4.dns-search example.com ipv4.method manual
  - name: Reloading Network
    service: 
      name: NetworkManager
      state: restarted 
  - name: Building Host File
    copy:
      src: /vagrant/hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'
      force: yes
  - name: Environment Packages Installed
    yum: 
      name: man-pages
      state: present
  - name: Starting services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - firewalld
  - name: Enabling IPV6
    sysctl:
      name: "{{ item }}"
      value: '0'
      sysctl_set: yes
    loop:
      - net.ipv6.conf.lo.disable_ipv6
      - net.ipv6.conf.all.disable_ipv6
  - name: Changing User Password
    shell: echo vagrant | sudo passwd vagrant --stdin
  - name: Changing Root Password
    shell: echo password | sudo passwd root --stdin
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      mode: 0644
      block: |
         #!/bin/bash
         #
         echo -e '
         #          _     _        _        _         _           _          _   _         _       
         #         / /\  /\ \     /\_\     / /\      /\ \        /\ \       /\_\/\_\ _   /\ \      
         #        / /  \ \ \ \   / / /    / /  \     \_\ \      /  \ \     / / / / //\_\/  \ \     
         #       / / /\ \_\ \ \_/ / /    / / /\ \__  /\__ \    / /\ \ \   /\ \/ \ \/ / / /\ \ \    
         #      / / /\ \___\ \___/ /    / / /\ \___\/ /_ \ \  / / /\ \_\ /  \____\__/ /\/_/\ \ \   
         #      \ \ \ \/___/\ \ \_/     \ \ \ \/___/ / /\ \ \/ /_/_ \/_// /\/________/     / / /   
         #       \ \ \       \ \ \       \ \ \    / / /  \/_/ /____/\  / / /\/_// / /     / / /    
         #   _    \ \ \       \ \ \  _    \ \ \  / / /     / /\____\/ / / /    / / /     / / /  _  
         #  /_/\__/ / /        \ \ \/_/\__/ / / / / /     / / /______/ / /    / / /     / / /_/\_\ 
         #  \ \/___/ /          \ \_\ \/___/ / /_/ /     / / /_______\/_/    / / /     / /_____/ / 
         #   \_____\/            \/_/\_____\/  \_\/      \/__________/       \/_/      \________/  
         #                                                                                         
         '"#
         # You are logged into \"`hostname`\" as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         #
         # For root - use \`sudo\` or \`sudo su -\`
         #
         # Repo BAaseOS/AppStream 
         # Available to use from http://repo.example.com/BaseOS 
         # and http://repo.example.com/AppStream
         # 
         # There are also two additional NICs and drives.
         "
  - name: Adjusting Services and Rebooting
    selinux:
      state: enforcing
      policy: targeted
